import {defineArrayMember, defineField, defineType} from 'sanity'

const TIER_OPTIONS = [
  {title: 'Featured', value: 'featured'},
  {title: 'In the journal', value: 'journal'},
  {title: 'Nominated', value: 'nominated'},
]

const CATEGORY_OPTIONS = [
  {title: 'Makers', value: 'Makers'},
  {title: 'Food & drink', value: 'Food & drink'},
  {title: 'Community', value: 'Community'},
  {title: 'Sport', value: 'Sport'},
  {title: 'Culture', value: 'Culture'},
]

export const person = defineType({
  name: 'person',
  title: 'Person',
  type: 'document',
  groups: [
    {name: 'directory', title: 'Directory card', default: true},
    {name: 'hero', title: 'Hero'},
    {name: 'story', title: 'Story'},
    {name: 'gallery', title: 'Gallery & quote'},
    {name: 'qa', title: 'Quick questions'},
    {name: 'timeline', title: 'Timeline'},
    {name: 'cta', title: 'Places & CTA'},
    {name: 'meta', title: 'SEO'},
  ],
  fields: [
    defineField({name: 'name', title: 'Full name', type: 'string', group: 'hero', validation: (Rule) => Rule.required()}),
    defineField({
      name: 'slug',
      title: 'Slug',
      type: 'slug',
      options: {source: 'name'},
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'order',
      title: 'Order',
      type: 'number',
      description: 'Sequences the directory listing. Lower numbers appear first.',
      group: 'directory',
      validation: (Rule) => Rule.required().integer().positive(),
    }),
    defineField({
      name: 'tier',
      title: 'Directory tier',
      type: 'string',
      description: 'Drives the badge and CTA on the directory listing card. "Featured" also makes them eligible for the spotlight card.',
      options: {list: TIER_OPTIONS},
      initialValue: 'nominated',
      group: 'directory',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'category',
      title: 'Directory category',
      type: 'string',
      options: {list: CATEGORY_OPTIONS},
      group: 'directory',
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'role', title: 'Role', type: 'string', description: 'e.g. "Tailor".', group: 'directory', validation: (Rule) => Rule.required()}),
    defineField({name: 'handle', title: 'Handle', type: 'string', description: 'e.g. "@nualamends".', group: 'directory'}),
    defineField({
      name: 'cardCoverImage',
      title: 'Card cover image',
      type: 'image',
      options: {hotspot: true},
      description: 'Wide cover photo for the directory card. Falls back to the portrait image when unset.',
      group: 'directory',
    }),
    defineField({
      name: 'cardLine',
      title: 'Card teaser line',
      type: 'text',
      rows: 2,
      description: 'Short one-liner for the directory card. Falls back to the tagline when unset.',
      group: 'directory',
    }),
    defineField({
      name: 'cardTags',
      title: 'Card tags',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      description: 'Small pills on the directory card, e.g. "Alterations", "Sewing night".',
      group: 'directory',
    }),
    defineField({
      name: 'eyebrow',
      title: 'Eyebrow badge',
      type: 'string',
      initialValue: 'Featured person',
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'area', title: 'Area', type: 'string', description: 'e.g. "West Street".', group: 'hero', validation: (Rule) => Rule.required()}),
    defineField({
      name: 'heroFirstName',
      title: 'Hero heading — first line',
      type: 'string',
      description: 'e.g. "Nuala". Rendered large on its own line.',
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'heroLastName',
      title: 'Hero heading — second line',
      type: 'string',
      description: 'e.g. "Kerrigan." Include trailing punctuation. Rendered in gold.',
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'tagline', title: 'Tagline', type: 'text', rows: 2, group: 'hero', validation: (Rule) => Rule.required()}),
    defineField({
      name: 'portraitImage',
      title: 'Portrait image',
      type: 'image',
      options: {hotspot: true},
      group: 'hero',
      validation: (Rule) => Rule.required(),
    }),
    defineField({name: 'featuredDate', title: 'Featured date', type: 'date', group: 'hero'}),

    defineField({
      name: 'marqueeTags',
      title: 'Marquee tags',
      type: 'array',
      of: [defineArrayMember({type: 'string'})],
      description: 'Short repeating chips in the gold banner, e.g. "Hems", "Zips".',
      group: 'story',
    }),
    defineField({name: 'statValue', title: 'Big stat value', type: 'string', description: 'e.g. "30".', group: 'story'}),
    defineField({name: 'statCaption', title: 'Big stat caption', type: 'text', rows: 2, group: 'story'}),
    defineField({
      name: 'facts',
      title: 'Facts',
      type: 'array',
      of: [defineArrayMember({type: 'personFact'})],
      group: 'story',
    }),
    defineField({name: 'leadIn', title: 'Story lead-in', type: 'text', rows: 2, group: 'story'}),
    defineField({name: 'leadHighlight', title: 'Story lead — highlighted continuation', type: 'text', rows: 2, group: 'story'}),
    defineField({
      name: 'storyParagraphs',
      title: 'Story paragraphs',
      type: 'array',
      of: [defineArrayMember({type: 'text', rows: 3})],
      group: 'story',
    }),

    defineField({
      name: 'galleryMainImage',
      title: 'Main gallery image',
      type: 'image',
      options: {hotspot: true},
      group: 'gallery',
    }),
    defineField({name: 'galleryMainCaption', title: 'Main image caption', type: 'string', group: 'gallery'}),
    defineField({name: 'quote', title: 'Pull quote', type: 'text', rows: 2, group: 'gallery'}),
    defineField({
      name: 'gallerySideImage',
      title: 'Side gallery image',
      type: 'image',
      options: {hotspot: true},
      group: 'gallery',
    }),

    defineField({name: 'qaHeading', title: 'Heading', type: 'string', initialValue: 'Six quick questions.', group: 'qa'}),
    defineField({
      name: 'qaItems',
      title: 'Questions & answers',
      type: 'array',
      of: [defineArrayMember({type: 'personQa'})],
      group: 'qa',
    }),

    defineField({name: 'timelineHeadingLine1', title: 'Heading — first line', type: 'string', group: 'timeline'}),
    defineField({name: 'timelineHeadingLine2', title: 'Heading — second line (gold)', type: 'string', group: 'timeline'}),
    defineField({
      name: 'timelineEntries',
      title: 'Timeline entries',
      type: 'array',
      of: [defineArrayMember({type: 'personTimelineEntry'})],
      group: 'timeline',
    }),

    defineField({
      name: 'ctaImage',
      title: 'Footer image',
      type: 'image',
      options: {hotspot: true},
      group: 'cta',
    }),
    defineField({name: 'placesHeading', title: 'Places heading', type: 'string', initialValue: "Where you'll find her", group: 'cta'}),
    defineField({
      name: 'places',
      title: 'Places',
      type: 'array',
      of: [defineArrayMember({type: 'personPlace'})],
      group: 'cta',
    }),
    defineField({name: 'ctaHeading', title: 'CTA heading', type: 'string', group: 'cta'}),
    defineField({name: 'ctaBody', title: 'CTA body', type: 'text', rows: 2, group: 'cta'}),
    defineField({name: 'nominateHref', title: '"Nominate someone" link', type: 'string', initialValue: '#', group: 'cta'}),
    defineField({name: 'moreHref', title: '"More people" link', type: 'string', initialValue: '/people', group: 'cta'}),

    defineField({name: 'seo', title: 'SEO', type: 'seo', group: 'meta'}),
  ],
  orderings: [{name: 'orderAsc', title: 'Order', by: [{field: 'order', direction: 'asc'}]}],
  preview: {
    select: {title: 'name', subtitle: 'role', media: 'portraitImage'},
  },
})
